[plugin]
prepend_previewers = [
    { name = "*.md", run = "glow" },
    { mime = "text/csv", run = "miller" },
    { mime = "audio/*", run = "exifaudio" },
    { mime = "application/x-bittorrent", run = "torrent-preview" },
    # Archive previewer
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
]
append_previewers = [{ name = "*", run = "hexyl" }]
