keys:
  - &primary age1aew0wld84lhcdte90ra0a4xhkwd2tlaanyr94xeffufpl3rls55qclcsfv
creation_rules:
  - path_regex: hosts/nixos/common/secrets.yaml
    key_groups:
      - age:
          - *primary
  - path_regex: hosts/nixos/inari/secrets.yaml
    key_groups:
      - age:
          - *primary
  - path_regex: home/features/desktop/wakatime/secrets.yaml
    key_groups:
      - age:
          - *primary
  - path_regex: home/features/cli/productivity/secrets.yaml
    key_groups:
      - age:
          - *primary
